server:
  port: 8041

spring:
  application:
    name: mall-shop  #?????

  #??zookeeper??????
  cloud:
    zookeeper:
      connect-string: 116.63.131.118:2181
      discovery:
        instance-host: 116.63.131.118

management:
  endpoints:
    web:
      exposure:
        include: '*'